In [1]:
import pandas as pd
import numpy as np

pd.cut() - segment and sort data into bins

value_counts()

In [4]:
#drop
df = pd.DataFrame(np.arange(12).reshape(3,4), columns=["A","B","C",'D'])
print(df)
a=df.drop(["B","C"],axis=1)
b=df.drop(columns=["B","C"])
print(a)
print(b,)
print(df.drop([0,2]))

   A  B   C   D
0  0  1   2   3
1  4  5   6   7
2  8  9  10  11
   A   D
0  0   3
1  4   7
2  8  11
   A   D
0  0   3
1  4   7
2  8  11
   A  B  C  D
1  4  5  6  7

In [6]:
midx= pd.MultiIndex(
    levels= [["llama", "cow", "falcon"], ["speed","weight","length"]],
    codes= [[0,0,0,1,1,1,2,2,2],[0,1,2,0,1,2,0,1,2]],
)
df = pd.DataFrame(index=midx, columns=["big","small"],
                        data=[
                                      [45,30],
                                      [200,100],
                                      [1.5,1],
                                      [30,20],
                                      [250,150],
                                      [1.5,0.8],
                                      [320,250],
                                      [1,0.8],
                                      [0.3,0.2],
                                ],
                 )

df

                 big  small
llama  speed    45.0   30.0
       weight  200.0  100.0
       length    1.5    1.0
cow    speed    30.0   20.0
       weight  250.0  150.0
       length    1.5    0.8
falcon speed   320.0  250.0
       weight    1.0    0.8
       length    0.3    0.2

In [10]:
# any()
df =pd.DataFrame({"A": [True, False], "B": [1,0]})
print(df)
df.any(axis="columns")

       A  B
0   True  1
1  False  0

0     True
1    False
dtype: bool

In [19]:
t=pd.date_range("20220101", periods=10)
df = pd.DataFrame(np.random.randn(10,4), index=t, columns = list("ABCD"))
df.head()

                   A         B         C         D
2022-01-01  0.753216 -1.263465  0.705940 -0.325538
2022-01-02 -0.589005  0.725853  0.157353  0.692715
2022-01-03  0.518850  0.340141 -1.349076 -0.239031
2022-01-04 -0.371623  0.364841  0.939414  1.355579
2022-01-05 -1.165305  1.364601 -1.949808  0.334011

In [5]:
df.T  #transpose

,2022-01-01,2022-01-02,2022-01-03,2022-01-04,2022-01-05,2022-01-06,2022-01-07,2022-01-08,2022-01-09,2022-01-10
A,-1.640049,-0.417374,0.617674,0.156724,0.774803,-1.024263,0.491805,2.237347,0.159009,-1.401310
B,1.178270,1.026946,-1.707422,-0.492087,0.521138,-2.244846,-1.053740,-0.583818,-1.853795,0.282487
C,-0.938596,-0.583346,-0.476122,2.290601,-0.023139,1.828607,-1.359825,-1.481843,1.261861,0.344316
D,-0.680865,0.499038,-0.198290,-0.583481,1.742165,0.762442,0.755148,-0.308959,-0.968793,-0.353076

In [6]:
df.sort_values(by="B")

                   A         B         C         D
2022-01-06 -1.024263 -2.244846  1.828607  0.762442
2022-01-09  0.159009 -1.853795  1.261861 -0.968793
2022-01-03  0.617674 -1.707422 -0.476122 -0.198290
2022-01-07  0.491805 -1.053740 -1.359825  0.755148
2022-01-08  2.237347 -0.583818 -1.481843 -0.308959
2022-01-04  0.156724 -0.492087  2.290601 -0.583481
2022-01-10 -1.401310  0.282487  0.344316 -0.353076
2022-01-05  0.774803  0.521138 -0.023139  1.742165
2022-01-02 -0.417374  1.026946 -0.583346  0.499038
2022-01-01 -1.640049  1.178270 -0.938596 -0.680865

In [9]:
df.loc[:, ["A","C"]]

                   A         C
2022-01-01 -1.640049 -0.938596
2022-01-02 -0.417374 -0.583346
2022-01-03  0.617674 -0.476122
2022-01-04  0.156724  2.290601
2022-01-05  0.774803 -0.023139
2022-01-06 -1.024263  1.828607
2022-01-07  0.491805 -1.359825
2022-01-08  2.237347 -1.481843
2022-01-09  0.159009  1.261861
2022-01-10 -1.401310  0.344316

In [10]:
df[:4]

                   A         B         C         D
2022-01-01 -1.640049  1.178270 -0.938596 -0.680865
2022-01-02 -0.417374  1.026946 -0.583346  0.499038
2022-01-03  0.617674 -1.707422 -0.476122 -0.198290
2022-01-04  0.156724 -0.492087  2.290601 -0.583481

In [14]:
df.iloc[3:5, [1,3,0]]

                   B         D         A
2022-01-04 -0.492087 -0.583481  0.156724
2022-01-05  0.521138  1.742165  0.774803

In [15]:
df[df > 0]

                   A         B         C         D
2022-01-01       NaN  1.178270       NaN       NaN
2022-01-02       NaN  1.026946       NaN  0.499038
2022-01-03  0.617674       NaN       NaN       NaN
2022-01-04  0.156724       NaN  2.290601       NaN
2022-01-05  0.774803  0.521138       NaN  1.742165
2022-01-06       NaN       NaN  1.828607  0.762442
2022-01-07  0.491805       NaN       NaN  0.755148
2022-01-08  2.237347       NaN       NaN       NaN
2022-01-09  0.159009       NaN  1.261861       NaN
2022-01-10       NaN  0.282487  0.344316       NaN

In [2]:
dataset = pd.read_csv("https://raw.githubusercontent.com/google/yggdrasil-decision-forests/main/yggdrasil_decision_forests/test_data/dataset/adult_train.csv")
dataset.index[dataset['education'] == 'Some-college']

Index([    1,     3,     5,    14,    18,    19,    24,    33,    34,    42,
       ...
       22736, 22740, 22741, 22747, 22753, 22755, 22763, 22764, 22778, 22785],
      dtype='int64', length=5077)

In [5]:
dataset.iloc[3]

age                               30
workclass                    Private
fnlwgt                        361742
education               Some-college
education_num                     10
marital_status    Married-civ-spouse
occupation           Exec-managerial
relationship                 Husband
race                           White
sex                             Male
capital_gain                       0
capital_loss                       0
hours_per_week                    50
native_country         United-States
income                         <=50K
Name: 3, dtype: object